data:
  class: ["real"]
  dataset: ModelNet10
  scan: 10000
  dim: 3
  data_type: psr_full
  input_type: pointcloud
  path: /mnt/raphael/ModelNet10
  num_gt_points: 10000
  num_offset: 7
  pointcloud_n: null
  pointcloud_noise: null
  pointcloud_outlier_ratio: null
  train_split: train
  val_split: test
  test_split: test
sensor:
  mode: norm+   # uniform sampling at mean_neighborhood*[-2 -1 1 2] + 1 non-uniform outside sample per point = closest sample point of any other LOS
  vector: sensor
  stepsi: [-2, -1]
  stepso: [ 1, 2, 4 ]
  sampling: uniform
  factor: neighborhood # or neighborhood
  ident_dim: 2
model:
  grid_res: 128 # poisson grid resolution
  psr_sigma: 2
  psr_tanh: True
  normal_normalize: False
  predict_normal: True
  predict_offset: True
  c_dim: 32
  s_offset: 0.001
  encoder: local_pool_pointnet
  encoder_kwargs:
    hidden_dim: 32
    plane_type: 'grid'
    grid_resolution: 32
    unet3d: True
    unet3d_kwargs:
      num_levels: 3
      f_maps: 32
      in_channels: 32
      out_channels: 32
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
train:
  batch_size: 8
  lr: 5e-4
#  out_dir: /home/rsulzer/data/ModelNet10_out/sap/scan43/conventional
  out_dir: /mnt/raphael/ModelNet10_out/sap/scan42/uniform_neighborhood_5
  load_model: model_best
  w_psr: 1
  model_selection_metric: psr_l2
  print_every: 100
  checkpoint_every: 2000
  validate_every: 2000
  backup_every: 10000
  total_epochs: 400000
  visualize_every: 500000
  exp_pcl: True
  exp_mesh: True
  n_workers: 3
  n_workers_val: 3
generation:
  batch_size: 100000
  exp_gt: False
  exp_oracle: False
  exp_input: False
  vis_n_outputs: 100000
  generate_mesh: True
  generate_pointcloud: False
  generation_dir: generation
  copy_input: false
  use_sampling: false
  psr_resolution: 128
  psr_sigma: 2